### ISSUE TITLE
Hyperparameter tuning fails because of .ix

### ISSUE THREAD

**Issue by sahbic** [sassoftware/python-pipefitter#2]
hyperparameter tuning fails in the provided example

```
hpt = HyperParameterTuning(
          estimator=DecisionTree(target='label', 
              inputs=['a'+str(i) for i in range(50)]),
          param_grid=param_grid, 
          cv=3)

hpt.gridsearch(casdata)
```

with the following error

> 'SASDataFrame' object has no attribute 'ix' error

the reason seems to be that .ix is deprecated

**Comment by kesmit13** [comment]
Fixed with commits c58d78e and 4d3afe0.
