### ISSUE TITLE
score method cannot be used in another CAS session

### ISSUE THREAD

**Issue by sahbic** [sassoftware/python-pipefitter#5]
## Issue

The `score` method fails when used in a CAS session that is different from the CAS session used for `fit`

![image](https://user-images.githubusercontent.com/4807254/114537063-0a5c3b00-9c52-11eb-9fc5-c2a9416e4b41.png)

#### Possible explanation:
The model table has a session scope.

## Desired behavior

Be able to fit the model and score it in two different sessions.

**Comment by kesmit13** [comment]
CAS doesn't allow tables to be seen across sessions unless they have been promoted to a global table. You can use the `table.promote` action on your table to make it global, then it will be accessible from all sessions.

**Comment by sahbic** [comment]
Thanks, this workaround solves the issue.
We need to access the model table to be able to promote it, this can be done using **model.data**  attribute (not documented)
